import { db } from './index'
import { users, decks, cards } from './schema'
import { v4 as uuidv4 } from 'uuid'
import bcrypt from 'bcryptjs'

// const db = await getDb()
const SYSTEM_USER_ID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

interface CardData {
  front: string
  back: string
  hint?: string
}

interface DeckData {
  id: string
  name: string
  description: string
  category: string
  difficulty: string
  language: string
  deckIcon: string
  tags: string[]
  cards: CardData[]
}

const HSK_DECKS: DeckData[] = [
  {
    id: 'hsk-1-greetings',
    name: 'HSK 1 - Greetings & Basics',
    description: 'Essential Chinese greetings, numbers, and basic phrases for beginners',
    category: 'hsk',
    difficulty: 'beginner',
    language: 'chinese',
    deckIcon: 'chinese',
    tags: ['hsk1', 'beginner', 'greetings', 'numbers'],
    cards: [
      { front: '你好', back: 'Hello', hint: 'nǐ hǎo' },
      { front: '谢谢', back: 'Thank you', hint: 'xiè xie' },
      { front: '再见', back: 'Goodbye', hint: 'zài jiàn' },
      { front: '请', back: 'Please', hint: 'qǐng' },
      { front: '对不起', back: 'Sorry', hint: 'duì bu qǐ' },
      { front: '没关系', back: "It's okay / No problem", hint: 'méi guān xi' },
      { front: '是', back: 'Yes / To be', hint: 'shì' },
      { front: '不是', back: 'No / Not', hint: 'bù shì' },
      { front: '我', back: 'I / Me', hint: 'wǒ' },
      { front: '你', back: 'You', hint: 'nǐ' },
      { front: '他', back: 'He / Him', hint: 'tā' },
      { front: '她', back: 'She / Her', hint: 'tā' },
      { front: '我们', back: 'We / Us', hint: 'wǒ men' },
      { front: '他们', back: 'They / Them', hint: 'tā men' },
      { front: '这个', back: 'This', hint: 'zhè gè' },
      { front: '那个', back: 'That', hint: 'nèi gè' },
      { front: '谁', back: 'Who', hint: 'shuí' },
      { front: '什么', back: 'What', hint: 'shén me' },
      { front: '哪', back: 'Which / Where', hint: 'nǎ' },
      { front: '为什么', back: 'Why', hint: 'wèi shén me' },
      { front: '一', back: 'One', hint: 'yī' },
      { front: '二', back: 'Two', hint: 'èr' },
      { front: '三', back: 'Three', hint: 'sān' },
      { front: '四', back: 'Four', hint: 'sì' },
      { front: '五', back: 'Five', hint: 'wǔ' },
      { front: '六', back: 'Six', hint: 'liù' },
      { front: '七', back: 'Seven', hint: 'qī' },
      { front: '八', back: 'Eight', hint: 'bā' },
      { front: '九', back: 'Nine', hint: 'jiǔ' },
      { front: '十', back: 'Ten', hint: 'shí' },
      { front: '百', back: 'Hundred', hint: 'bǎi' },
      { front: '千', back: 'Thousand', hint: 'qiān' },
      { front: '钱', back: 'Money', hint: 'qián' },
      { front: '多少', back: 'How many / How much', hint: 'duō shao' },
      { front: '大', back: 'Big / Large', hint: 'dà' },
      { front: '小', back: 'Small / Little', hint: 'xiǎo' },
      { front: '好', back: 'Good / Well', hint: 'hǎo' },
      { front: '不好', back: 'Not good / Bad', hint: 'bù hǎo' },
      { front: '很', back: 'Very', hint: 'hěn' },
      { front: '也', back: 'Also / Too', hint: 'yě' },
      { front: '都', back: 'All / Both', hint: 'dōu' },
      { front: '不', back: 'No / Not', hint: 'bù' },
      { front: '吗', back: 'Question marker (吗)', hint: 'ma' },
      { front: '呢', back: 'And you? / What about?', hint: 'ne' },
      { front: '爸爸', back: 'Dad / Father', hint: 'bà ba' },
      { front: '妈妈', back: 'Mom / Mother', hint: 'mā ma' },
      { front: '老师', back: 'Teacher', hint: 'lǎo shī' },
      { front: '学生', back: 'Student', hint: 'xué shēng' },
      { front: '朋友', back: 'Friend', hint: 'péng you' },
      { front: '人', back: 'Person / People', hint: 'rén' },
      { front: '家', back: 'Home / Family', hint: 'jiā' },
      { front: '学校', back: 'School', hint: 'xué xiào' },
      { front: '公司', back: 'Company', hint: 'gōng sī' },
      { front: '工作', back: 'Work / Job', hint: 'gōng zuò' },
      { front: '时间', back: 'Time', hint: 'shí jiān' },
      { front: '今天', back: 'Today', hint: 'jīn tiān' },
      { front: '明天', back: 'Tomorrow', hint: 'míng tiān' },
      { front: '昨天', back: 'Yesterday', hint: 'zuó tiān' },
      { front: '早上', back: 'Morning', hint: 'zǎo shang' },
      { front: '中午', back: 'Noon / Afternoon', hint: 'zhōng wǔ' },
      { front: '晚上', back: 'Evening / Night', hint: 'wǎn shang' },
      { front: '现在', back: 'Now', hint: 'xiàn zài' },
      { front: '吃', back: 'To eat', hint: 'chī' },
      { front: '喝', back: 'To drink', hint: 'hē' },
      { front: '水', back: 'Water', hint: 'shuǐ' },
      { front: '茶', back: 'Tea', hint: 'chá' },
      { front: '咖啡', back: 'Coffee', hint: 'kā fēi' },
      { front: '米饭', back: 'Rice', hint: 'mǐ fàn' },
      { front: '苹果', back: 'Apple', hint: 'píng guǒ' },
      { front: '喜欢', back: 'To like', hint: 'xǐ huan' },
      { front: '爱', back: 'To love', hint: 'ài' },
      { front: '看', back: 'To look / To watch', hint: 'kàn' },
      { front: '听', back: 'To listen / To hear', hint: 'tīng' },
      { front: '说', back: 'To speak / To say', hint: 'shuō' },
      { front: '读', back: 'To read', hint: 'dú' },
      { front: '写', back: 'To write', hint: 'xiě' },
      { front: '学', back: 'To learn / To study', hint: 'xué' },
      { front: '知道', back: 'To know (fact)', hint: 'zhī dào' },
      { front: '会', back: 'Can / To be able to', hint: 'huì' },
      { front: '能', back: 'Can / To be able to', hint: 'néng' },
      { front: '去', back: 'To go', hint: 'qù' },
      { front: '来', back: 'To come', hint: 'lái' },
      { front: '回', back: 'To return / To go back', hint: 'huí' },
      { front: '买', back: 'To buy', hint: 'mǎi' },
      { front: '卖', back: 'To sell', hint: 'mài' },
    ],
  },
  {
    id: 'hsk-2-daily',
    name: 'HSK 2 - Daily Life',
    description: 'Vocabulary for daily routines, shopping, transportation, and weather',
    category: 'hsk',
    difficulty: 'beginner',
    language: 'chinese',
    deckIcon: 'chinese',
    tags: ['hsk2', 'beginner', 'daily', 'shopping'],
    cards: [
      { front: '电脑', back: 'Computer', hint: 'diàn nǎo' },
      { front: '手机', back: 'Mobile phone', hint: 'shǒu jī' },
      { front: '电视', back: 'Television', hint: 'diàn shì' },
      { front: '电影', back: 'Movie / Film', hint: 'diàn yǐng' },
      { front: '音乐', back: 'Music', hint: 'yīn yuè' },
      { front: '书', back: 'Book', hint: 'shū' },
      { front: '字', back: 'Character / Word', hint: 'zì' },
      { front: '学习', back: 'To study / To learn', hint: 'xué xí' },
      { front: '上课', back: 'To attend class', hint: 'shàng kè' },
      { front: '考试', back: 'Exam / Test', hint: 'kǎo shì' },
      { front: '房间', back: 'Room', hint: 'fáng jiān' },
      { front: '厕所', back: 'Toilet / Bathroom', hint: 'cè suǒ' },
      { front: '门', back: 'Door / Gate', hint: 'mén' },
      { front: '窗', back: 'Window', hint: 'chuāng' },
      { front: '桌子', back: 'Table / Desk', hint: 'zhuō zi' },
      { front: '椅子', back: 'Chair', hint: 'yǐ zi' },
      { front: '床', back: 'Bed', hint: 'chuáng' },
      { front: '衣服', back: 'Clothes', hint: 'yī fu' },
      { front: '鞋', back: 'Shoes', hint: 'xié' },
      { front: '颜色', back: 'Color', hint: 'yán sè' },
      { front: '红', back: 'Red', hint: 'hóng' },
      { front: '蓝', back: 'Blue', hint: 'lán' },
      { front: '白', back: 'White', hint: 'bái' },
      { front: '黑', back: 'Black', hint: 'hēi' },
      { front: '黄', back: 'Yellow', hint: 'huáng' },
      { front: '绿', back: 'Green', hint: 'lǜ' },
      { front: '商店', back: 'Shop / Store', hint: 'shāng diàn' },
      { front: '市场', back: 'Market', hint: 'shì chǎng' },
      { front: '超市', back: 'Supermarket', hint: 'chāo shì' },
      { front: '医院', back: 'Hospital', hint: 'yī yuàn' },
      { front: '药', back: 'Medicine', hint: 'yào' },
      { front: '医生', back: 'Doctor', hint: 'yī shēng' },
      { front: '银行', back: 'Bank', hint: 'yín háng' },
      { front: '邮局', back: 'Post office', hint: 'yóu jú' },
      { front: '地图', back: 'Map', hint: 'dì tú' },
      { front: '出租车', back: 'Taxi', hint: 'chū zū chē' },
      { front: '公共汽车', back: 'Bus', hint: 'gōng gòng qì chē' },
      { front: '地铁', back: 'Subway / Metro', hint: 'dì tiě' },
      { front: '火车', back: 'Train', hint: 'huǒ chē' },
      { front: '飞机', back: 'Airplane', hint: 'fēi jī' },
      { front: '机场', back: 'Airport', hint: 'jī chǎng' },
      { front: '车站', back: 'Station', hint: 'chē zhàn' },
      { front: '路', back: 'Road / Way', hint: 'lù' },
      { front: '天气', back: 'Weather', hint: 'tiān qì' },
      { front: '下雨', back: 'To rain', hint: 'xià yǔ' },
      { front: '下雪', back: 'To snow', hint: 'xià xuě' },
      { front: '冷', back: 'Cold', hint: 'lěng' },
      { front: '热', back: 'Hot', hint: 'rè' },
      { front: '暖和', back: 'Warm', hint: 'nuǎn huo' },
      { front: '凉快', back: 'Cool', hint: 'liáng kuai' },
      { front: '风', back: 'Wind', hint: 'fēng' },
      { front: '云', back: 'Cloud', hint: 'yún' },
      { front: '太阳', back: 'Sun', hint: 'tài yáng' },
      { front: '月', back: 'Moon / Month', hint: 'yuè' },
      { front: '星', back: 'Star', hint: 'xīng' },
      { front: '年', back: 'Year', hint: 'nián' },
      { front: '星期', back: 'Week', hint: 'xīng qī' },
      { front: '开始', back: 'To start / To begin', hint: 'kāi shǐ' },
      { front: '结束', back: 'To end', hint: 'jié shù' },
      { front: '做', back: 'To do / To make', hint: 'zuò' },
      { front: '想', back: 'To think / To want', hint: 'xiǎng' },
      { front: '觉得', back: 'To think / To feel', hint: 'jué de' },
      { front: '认为', back: 'To think / To believe', hint: 'rèn wéi' },
      { front: '生活', back: 'Life / To live', hint: 'shēng huó' },
      { front: '世界', back: 'World', hint: 'shì jiè' },
      { front: '国家', back: 'Country', hint: 'guó jiā' },
      { front: '中国', back: 'China', hint: 'zhōng guó' },
      { front: '美国', back: 'United States', hint: 'měi guó' },
      { front: '日本', back: 'Japan', hint: 'rì běn' },
      { front: '英国', back: 'United Kingdom', hint: 'yīng guó' },
      { front: '法国', back: 'France', hint: 'fǎ guó' },
      { front: '德国', back: 'Germany', hint: 'dé guó' },
      { front: '韩国', back: 'South Korea', hint: 'hán guó' },
      { front: '新加坡', back: 'Singapore', hint: 'xīn jiā pō' },
      { front: '泰国', back: 'Thailand', hint: 'tài guó' },
      { front: '越南', back: 'Vietnam', hint: 'yuè nán' },
      { front: '印度', back: 'India', hint: 'yìn dù' },
      { front: '俄语', back: 'Russian', hint: 'é yǔ' },
      { front: '法语', back: 'French', hint: 'fǎ yǔ' },
      { front: '德语', back: 'German', hint: 'dé yǔ' },
      { front: '韩语', back: 'Korean', hint: 'hán yǔ' },
      { front: '中文', back: 'Chinese (language)', hint: 'zhōng wén' },
      { front: '汉字', back: 'Chinese character', hint: 'hàn zì' },
      { front: '拼音', back: 'Pinyin', hint: 'pīn yīn' },
      { front: '英语', back: 'English', hint: 'yīng yǔ' },
      { front: '住', back: 'To live / To reside', hint: 'zhù' },
      { front: '做饭', back: 'To cook', hint: 'zuò fàn' },
      { front: '睡觉', back: 'To sleep', hint: 'shuì jiào' },
      { front: '起床', back: 'To get up', hint: 'qǐ chuáng' },
      { front: '洗澡', back: 'To take a shower', hint: 'xǐ zǎo' },
      { front: '跑步', back: 'To run / Jogging', hint: 'pǎo bù' },
      { front: '运动', back: 'Sports / Exercise', hint: 'yùn dòng' },
      { front: '休息', back: 'To rest', hint: 'xiū xi' },
      { front: '旅行', back: 'To travel', hint: 'lǚ xíng' },
    ],
  },
  {
    id: 'hsk-3-travel',
    name: 'HSK 3 - Travel & Shopping',
    description: 'Vocabulary for traveling, shopping, dining, and social situations',
    category: 'hsk',
    difficulty: 'intermediate',
    language: 'chinese',
    deckIcon: 'chinese',
    tags: ['hsk3', 'intermediate', 'travel', 'shopping'],
    cards: [
      { front: '预订', back: 'To book / To reserve', hint: 'yù dìng' },
      { front: '酒店', back: 'Hotel', hint: 'jiǔ diàn' },
      { front: '前台', back: 'Reception / Front desk', hint: 'qián tái' },
      { front: '退房', back: 'To check out', hint: 'tuì fáng' },
      { front: '入住', back: 'To check in', hint: 'rù zhù' },
      { front: '行李', back: 'Luggage / Baggage', hint: 'xíng li' },
      { front: '护照', back: 'Passport', hint: 'hù zhào' },
      { front: '签证', back: 'Visa', hint: 'qiān zhèng' },
      { front: '票', back: 'Ticket', hint: 'piào' },
      { front: '便宜', back: 'Cheap / Inexpensive', hint: 'pián yi' },
      { front: '贵', back: 'Expensive / Valuable', hint: 'guì' },
      { front: '打折', back: 'To give a discount', hint: 'dǎ zhé' },
      { front: '付钱', back: 'To pay (money)', hint: 'fù qián' },
      { front: '找钱', back: 'To give change', hint: 'zhǎo qián' },
      { front: '刷卡', back: 'To swipe / Pay by card', hint: 'shuā kǎ' },
      { front: '现金', back: 'Cash', hint: 'xiàn jīn' },
      { front: '餐厅', back: 'Restaurant', hint: 'cān tīng' },
      { front: '菜单', back: 'Menu', hint: 'cài dān' },
      { front: '服务员', back: 'Waiter / Waitress', hint: 'fú wù yuán' },
      { front: '好吃', back: 'Delicious / Tasty', hint: 'hǎo chī' },
      { front: '饿', back: 'Hungry', hint: 'è' },
      { front: '渴', back: 'Thirsty', hint: 'kě' },
      { front: '饱', back: 'Full (after eating)', hint: 'bǎo' },
      { front: '点菜', back: 'To order (food)', hint: 'diǎn cài' },
      { front: '买单', back: 'To pay the bill', hint: 'mǎi dān' },
      { front: '筷子', back: 'Chopsticks', hint: 'kuài zi' },
      { front: '叉子', back: 'Fork', hint: 'chā zi' },
      { front: '刀子', back: 'Knife', hint: 'dāo zi' },
      { front: '勺子', back: 'Spoon', hint: 'sháo zi' },
      { front: '碗', back: 'Bowl', hint: 'wǎn' },
      { front: '盘子', back: 'Plate / Dish', hint: 'pán zi' },
      { front: '杯子', back: 'Cup / Glass', hint: 'bēi zi' },
      { front: '瓶', back: 'Bottle', hint: 'píng' },
      { front: '馆子', back: 'Restaurant (informal)', hint: 'guǎn zi' },
      { front: '味道', back: 'Taste / Flavor', hint: 'wèi dào' },
      { front: '辣', back: 'Spicy / Hot', hint: 'là' },
      { front: '甜', back: 'Sweet', hint: 'tián' },
      { front: '咸', back: 'Salty', hint: 'xián' },
      { front: '酸', back: 'Sour', hint: 'suān' },
      { front: '苦', back: 'Bitter', hint: 'kǔ' },
      { front: '风景', back: 'Scenery / Landscape', hint: 'fēng jǐng' },
      { front: '漂亮', back: 'Beautiful / Pretty', hint: 'piào liang' },
      { front: '美', back: 'Beautiful', hint: 'měi' },
      { front: '可爱', back: 'Cute / Lovely', hint: 'kě ài' },
      { front: '帅', back: 'Handsome', hint: 'shuài' },
      { front: '高', back: 'Tall / High', hint: 'gāo' },
      { front: '矮', back: 'Short (height)', hint: 'ǎi' },
      { front: '长', back: 'Long', hint: 'cháng' },
      { front: '短', back: 'Short (length)', hint: 'duǎn' },
      { front: '新', back: 'New', hint: 'xīn' },
      { front: '旧', back: 'Old (used)', hint: 'jiù' },
      { front: '快', back: 'Fast / Quick', hint: 'kuài' },
      { front: '慢', back: 'Slow', hint: 'màn' },
      { front: '容易', back: 'Easy', hint: 'róng yì' },
      { front: '难', back: 'Difficult / Hard', hint: 'nán' },
      { front: '累', back: 'Tired', hint: 'lèi' },
      { front: '忙', back: 'Busy', hint: 'máng' },
      { front: '闲', back: 'Free / Idle', hint: 'xián' },
      { front: '快乐', back: 'Happy / Joyful', hint: 'kuài lè' },
      { front: '高兴', back: 'Happy / Glad', hint: 'gāo xìng' },
      { front: '开心', back: 'Happy / Cheerful', hint: 'kāi xīn' },
      { front: '难过', back: 'Sad / Upset', hint: 'nán guò' },
      { front: '生气', back: 'Angry', hint: 'shēng qì' },
      { front: '害怕', back: 'Scared / Afraid', hint: 'hài pà' },
      { front: '担心', back: 'To worry', hint: 'dān xīn' },
      { front: '着急', back: 'Anxious / Worried', hint: 'zháo jí' },
      { front: '安静', back: 'Quiet', hint: 'ān jìng' },
      { front: '热闹', back: 'Lively / Bustling', hint: 'rè nao' },
      { front: '挤', back: 'Crowded / To squeeze', hint: 'jǐ' },
      { front: '远', back: 'Far / Distant', hint: 'yuǎn' },
      { front: '近', back: 'Near / Close', hint: 'jìn' },
      { front: '左', back: 'Left', hint: 'zuǒ' },
      { front: '右', back: 'Right', hint: 'yòu' },
      { front: '前', back: 'Front / Before', hint: 'qián' },
      { front: '后', back: 'Back / Behind / After', hint: 'hòu' },
      { front: '里', back: 'Inside / In', hint: 'lǐ' },
      { front: '外', back: 'Outside / Out', hint: 'wài' },
      { front: '上', back: 'On / Up / Above', hint: 'shàng' },
      { front: '下', back: 'Under / Down / Below', hint: 'xià' },
      { front: '旁边', back: 'Beside / Next to', hint: 'páng biān' },
      { front: '中间', back: 'Middle / Center', hint: 'zhōng jiān' },
      { front: '对面', back: 'Opposite / Across', hint: 'duì miàn' },
      { front: '一直', back: 'Always / All the way', hint: 'yì zhí' },
      { front: '已经', back: 'Already', hint: 'yǐ jīng' },
      { front: '还', back: 'Still / Also / Yet', hint: 'hái' },
      { front: '再', back: 'Again / Then', hint: 'zài' },
      { front: '才', back: 'Just / Only then', hint: 'cái' },
      { front: '就', back: 'Then / Only / Just', hint: 'jiù' },
      { front: '非常', back: 'Very / Extremely', hint: 'fēi cháng' },
      { front: '特别', back: 'Special / Particularly', hint: 'tè bié' },
      { front: '真', back: 'Real / Truly / Really', hint: 'zhēn' },
      { front: '最', back: 'Most / -est', hint: 'zuì' },
      { front: '太', back: 'Too (excessively)', hint: 'tài' },
      { front: '更', back: 'Even more / To change', hint: 'gèng' },
      { front: '越', back: 'More and more / The more', hint: 'yuè' },
      { front: '又', back: 'Again / Also / Both', hint: 'yòu' },
      { front: '还是', back: 'Or / Still', hint: 'hái shi' },
      { front: '但是', back: 'But / However', hint: 'dàn shì' },
    ],
  },
  {
    id: 'hsk-4-work',
    name: 'HSK 4 - Work & Business',
    description: 'Vocabulary for professional settings, meetings, and workplace communication',
    category: 'hsk',
    difficulty: 'intermediate',
    language: 'chinese',
    deckIcon: 'chinese',
    tags: ['hsk4', 'intermediate', 'business', 'work'],
    cards: [
      { front: '开会', back: 'To hold a meeting', hint: 'kāi huì' },
      { front: '会议', back: 'Meeting / Conference', hint: 'huì yì' },
      { front: '办公室', back: 'Office', hint: 'bàn gōng shì' },
      { front: '同事', back: 'Colleague / Coworker', hint: 'tóng shì' },
      { front: '老板', back: 'Boss', hint: 'lǎo bǎn' },
      { front: '员工', back: 'Employee / Staff', hint: 'yuán gōng' },
      { front: '面试', back: 'Job interview', hint: 'miàn shì' },
      { front: '简历', back: 'Resume / CV', hint: 'jiǎn lì' },
      { front: '工资', back: 'Wage / Salary', hint: 'gōng zī' },
      { front: '加班', back: 'To work overtime', hint: 'jiā bān' },
      { front: '请假', back: 'To ask for leave', hint: 'qǐng jià' },
      { front: '迟到', back: 'To be late', hint: 'chí dào' },
      { front: '早退', back: 'To leave early', hint: 'zǎo tuì' },
      { front: '出差', back: 'Business trip', hint: 'chū chāi' },
      { front: '辞职', back: 'To resign / To quit job', hint: 'cí zhí' },
      { front: '招聘', back: 'To recruit / To hire', hint: 'zhāo pìn' },
      { front: '申请', back: 'To apply / Application', hint: 'shēn qǐng' },
      { front: '合同', back: 'Contract', hint: 'hé tong' },
      { front: '项目', back: 'Project', hint: 'xiàng mù' },
      { front: '计划', back: 'Plan', hint: 'jì huà' },
      { front: '目标', back: 'Goal / Target', hint: 'mù biāo' },
      { front: '任务', back: 'Task / Mission', hint: 'rèn wù' },
      { front: '完成', back: 'To complete', hint: 'wán chéng' },
      { front: '成功', back: 'Success / To succeed', hint: 'chéng gōng' },
      { front: '失败', back: 'Failure / To fail', hint: 'shī bài' },
      { front: '经验', back: 'Experience', hint: 'jīng yàn' },
      { front: '能力', back: 'Ability / Capability', hint: 'néng lì' },
      { front: '水平', back: 'Level / Standard', hint: 'shuǐ píng' },
      { front: '专业', back: 'Major / Professional / Field of study', hint: 'zhuān yè' },
      { front: '研究', back: 'Research / To research', hint: 'yán jiū' },
      { front: '开发', back: 'To develop', hint: 'kāi fā' },
      { front: '管理', back: 'Management / To manage', hint: 'guǎn lǐ' },
      { front: '组织', back: 'Organization / To organize', hint: 'zǔ zhī' },
      { front: '领导', back: 'Leader / Leadership', hint: 'lǐng dǎo' },
      { front: '决定', back: 'Decision / To decide', hint: 'jué dìng' },
      { front: '讨论', back: 'Discussion / To discuss', hint: 'tǎo lùn' },
      { front: '问题', back: 'Question / Problem', hint: 'wèn tí' },
      { front: '解决', back: 'To solve / To resolve', hint: 'jiě jué' },
      { front: '建议', back: 'Suggestion / To suggest', hint: 'jiàn yì' },
      { front: '意见', back: 'Opinion / View', hint: 'yì jiàn' },
      { front: '联系', back: 'Contact / To contact', hint: 'lián xì' },
      { front: '通知', back: 'Notice / To notify', hint: 'tōng zhī' },
      { front: '报告', back: 'Report', hint: 'bào gào' },
      { front: '邮件', back: 'Email', hint: 'yóu jiàn' },
      { front: '信息', back: 'Information', hint: 'xìn xī' },
      { front: '资料', back: 'Materials / Data', hint: 'zī liào' },
      { front: '文件', back: 'Document / File', hint: 'wén jiàn' },
      { front: '打印机', back: 'Printer', hint: 'dǎ yìn jī' },
      { front: '复印机', back: 'Photocopier', hint: 'fù yìn jī' },
      { front: '签字', back: 'To sign (a document)', hint: 'qiān zì' },
      { front: '盖章', back: 'To stamp / To seal', hint: 'gài zhāng' },
      { front: '有效', back: 'Effective / Valid', hint: 'yǒu xiào' },
      { front: '过期', back: 'Expired / To expire', hint: 'guò qī' },
      { front: '取消', back: 'To cancel', hint: 'qǔ xiāo' },
      { front: '改变', back: 'To change / Change', hint: 'gǎi biàn' },
      { front: '提高', back: 'To improve / To enhance', hint: 'tí gāo' },
      { front: '增加', back: 'To increase / To add', hint: 'zēng jiā' },
      { front: '减少', back: 'To decrease / To reduce', hint: 'jiǎn shǎo' },
      { front: '影响', back: 'Influence / To affect', hint: 'yǐng xiǎng' },
      { front: '关系', back: 'Relationship / Relation', hint: 'guān xì' },
      { front: '合作', back: 'Cooperation / To cooperate', hint: 'hé zuò' },
      { front: '支持', back: 'Support / To support', hint: 'zhī chí' },
      { front: '帮助', back: 'Help / To help', hint: 'bāng zhù' },
      { front: '相信', back: 'To believe / To trust', hint: 'xiāng xìn' },
      { front: '理解', back: 'To understand / Understanding', hint: 'lǐ jiě' },
      { front: '了解', back: 'To know / To understand', hint: 'liǎo jiě' },
      { front: '熟悉', back: 'Familiar / To be familiar with', hint: 'shú xī' },
      { front: '重要', back: 'Important', hint: 'zhòng yào' },
      { front: '需要', back: 'Need / To need', hint: 'xū yào' },
      { front: '必须', back: 'Must / Have to', hint: 'bì xū' },
      { front: '应该', back: 'Should / Ought to', hint: 'yīng gāi' },
      { front: '可以', back: 'Can / May / Okay', hint: 'kě yǐ' },
      { front: '希望', back: 'Hope / To hope / To wish', hint: 'xī wàng' },
      { front: '愿意', back: 'Willing / To be willing', hint: 'yuàn yì' },
      { front: '可能', back: 'Possible / Maybe / Possibly', hint: 'kě néng' },
      { front: '当然', back: 'Of course / Certainly', hint: 'dāng rán' },
      { front: '实际', back: 'Actual / Reality', hint: 'shí jì' },
      { front: '基本', back: 'Basic / Fundamental', hint: 'jī běn' },
      { front: '一般', back: 'General / Usually / Ordinary', hint: 'yì bān' },
      { front: '特殊', back: 'Special / Special', hint: 'tè shū' },
      { front: '简单', back: 'Simple', hint: 'jiǎn dān' },
      { front: '复杂', back: 'Complex / Complicated', hint: 'fù zá' },
      { front: '明显', back: 'Obvious / Clear', hint: 'míng xiǎn' },
      { front: '清楚', back: 'Clear / To be clear', hint: 'qīng chu' },
      { front: '完全', back: 'Complete / Completely', hint: 'wán quán' },
      { front: '真正', back: 'Real / Truly', hint: 'zhēn zhèng' },
      { front: '直接', back: 'Direct / Directly', hint: 'zhí jiē' },
      { front: '具体', back: 'Specific / Concrete', hint: 'jù tǐ' },
      { front: '大概', back: 'Probably / About / Rough', hint: 'dà gài' },
      { front: '总之', back: 'In short / In a word', hint: 'zǒng zhī' },
      { front: '而且', back: 'Moreover / And also', hint: 'ér qiě' },
      { front: '因此', back: 'Therefore / Thus', hint: 'yīn cǐ' },
      { front: '然后', back: 'Then / After that', hint: 'rán hòu' },
      { front: '不过', back: 'However / Only / But', hint: 'bù guò' },
      { front: '虽然', back: 'Although', hint: 'suī rán' },
      { front: '只要', back: 'As long as / Only need', hint: 'zhǐ yào' },
      { front: '除非', back: 'Unless', hint: 'chú fēi' },
      { front: '除了', back: 'Except / Besides', hint: 'chú le' },
      { front: '关于', back: 'About / Regarding', hint: 'guān yú' },
      { front: '按照', back: 'According to', hint: 'àn zhào' },
    ],
  },
  {
    id: 'hsk-5-advanced',
    name: 'HSK 5 - Abstract Topics',
    description: 'Advanced vocabulary for discussing abstract topics, opinions, and complex ideas',
    category: 'hsk',
    difficulty: 'advanced',
    language: 'chinese',
    deckIcon: 'chinese',
    tags: ['hsk5', 'advanced', 'abstract', 'discussion'],
    cards: [
      { front: '社会', back: 'Society', hint: 'shè huì' },
      { front: '文化', back: 'Culture', hint: 'wén huà' },
      { front: '历史', back: 'History', hint: 'lì shǐ' },
      { front: '传统', back: 'Tradition', hint: 'chuán tǒng' },
      { front: '现代', back: 'Modern / Contemporary', hint: 'xiàn dài' },
      { front: '发展', back: 'Development / To develop', hint: 'fā zhǎn' },
      { front: '进步', back: 'Progress / To progress', hint: 'jìn bù' },
      { front: '经济', back: 'Economy / Economic', hint: 'jīng jì' },
      { front: '政治', back: 'Politics / Political', hint: 'zhèng zhì' },
      { front: '法律', back: 'Law', hint: 'fǎ lǜ' },
      { front: '政策', back: 'Policy', hint: 'zhèng cè' },
      { front: '改革', back: 'Reform / To reform', hint: 'gǎi gé' },
      { front: '教育', back: 'Education', hint: 'jiào yù' },
      { front: '科学', back: 'Science', hint: 'kē xué' },
      { front: '技术', back: 'Technology / Technique', hint: 'jì shù' },
      { front: '环境', back: 'Environment', hint: 'huán jìng' },
      { front: '保护', back: 'Protection / To protect', hint: 'bǎo hù' },
      { front: '污染', back: 'Pollution', hint: 'wū rǎn' },
      { front: '资源', back: 'Resources', hint: 'zī yuán' },
      { front: '能源', back: 'Energy', hint: 'néng yuán' },
      { front: '人口', back: 'Population', hint: 'rén kǒu' },
      { front: '交通', back: 'Transportation / Traffic', hint: 'jiāo tōng' },
      { front: '安全', back: 'Safety / Security', hint: 'ān quán' },
      { front: '健康', back: 'Health / Healthy', hint: 'jiàn kāng' },
      { front: '医疗', back: 'Medical treatment', hint: 'yī liáo' },
      { front: '心理', back: 'Psychology / Psychological', hint: 'xīn lǐ' },
      { front: '精神', back: 'Spirit / Mental', hint: 'jīng shén' },
      { front: '思想', back: 'Thought / Thinking', hint: 'sī xiǎng' },
      { front: '概念', back: 'Concept', hint: 'gài niàn' },
      { front: '理论', back: 'Theory', hint: 'lǐ lùn' },
      { front: '原则', back: 'Principle', hint: 'yuán zé' },
      { front: '标准', back: 'Standard / Criterion', hint: 'biāo zhǔn' },
      { front: '价值', back: 'Value / Worth', hint: 'jià zhí' },
      { front: '意义', back: 'Meaning / Significance', hint: 'yì yì' },
      { front: '目的', back: 'Purpose / Goal', hint: 'mù dì' },
      { front: '原因', back: 'Reason / Cause', hint: 'yuán yīn' },
      { front: '结果', back: 'Result / Outcome', hint: 'jié guǒ' },
      { front: '效果', back: 'Effect / Result', hint: 'xiào guǒ' },
      { front: '程度', back: 'Degree / Level', hint: 'chéng dù' },
      { front: '范围', back: 'Scope / Range', hint: 'fàn wéi' },
      { front: '方面', back: 'Aspect / Respect', hint: 'fāng miàn' },
      { front: '情况', back: 'Situation / Condition', hint: 'qíng kuàng' },
      { front: '状态', back: 'State / Status', hint: 'zhuàng tài' },
      { front: '过程', back: 'Process', hint: 'guò chéng' },
      { front: '阶段', back: 'Stage / Phase', hint: 'jiē duàn' },
      { front: '机会', back: 'Opportunity / Chance', hint: 'jī huì' },
      { front: '条件', back: 'Condition / Requirement', hint: 'tiáo jiàn' },
      { front: '现实', back: 'Reality / Realistic', hint: 'xiàn shí' },
      { front: '理想', back: 'Ideal / Aspiration', hint: 'lǐ xiǎng' },
      { front: '态度', back: 'Attitude', hint: 'tài dù' },
      { front: '感情', back: 'Emotion / Feeling', hint: 'gǎn qíng' },
      { front: '心情', back: 'Mood / State of mind', hint: 'xīn qíng' },
      { front: '性格', back: 'Personality / Character', hint: 'xìng gé' },
      { front: '特点', back: 'Characteristic / Feature', hint: 'tè diǎn' },
      { front: '优点', back: 'Advantage / Merit', hint: 'yōu diǎn' },
      { front: '缺点', back: 'Disadvantage / Shortcoming', hint: 'quē diǎn' },
      { front: '挑战', back: 'Challenge', hint: 'tiǎo zhàn' },
      { front: '压力', back: 'Pressure / Stress', hint: 'yā lì' },
      { front: '竞争', back: 'Competition / To compete', hint: 'jìng zhēng' },
      { front: '交流', back: 'Exchange / Communication', hint: 'jiāo liú' },
      { front: '沟通', back: 'Communication / To communicate', hint: 'gōu tōng' },
      { front: '表达', back: 'Expression / To express', hint: 'biǎo dá' },
      { front: '表现', back: 'Performance / To show', hint: 'biǎo xiàn' },
      { front: '介绍', back: 'Introduction / To introduce', hint: 'jiè shào' },
      { front: '解释', back: 'Explanation / To explain', hint: 'jiě shì' },
      { front: '证明', back: 'Proof / To prove', hint: 'zhèng míng' },
      { front: '确认', back: 'Confirmation / To confirm', hint: 'què rèn' },
      { front: '记录', back: 'Record / To record', hint: 'jì lù' },
      { front: '分析', back: 'Analysis / To analyze', hint: 'fēn xī' },
      { front: '总结', back: 'Summary / To summarize', hint: 'zǒng jié' },
      { front: '包括', back: 'Include / Including', hint: 'bāo kuò' },
      { front: '涉及', back: 'Involve / Relate to', hint: 'shè jí' },
      { front: '代表', back: 'Representative / To represent', hint: 'dài biǎo' },
      { front: '主要', back: 'Main / Primary', hint: 'zhǔ yào' },
      { front: '次要', back: 'Secondary', hint: 'cì yào' },
      { front: '相对', back: 'Relative / Relatively', hint: 'xiāng duì' },
      { front: '绝对', back: 'Absolute / Absolutely', hint: 'jué duì' },
      { front: '普遍', back: 'Universal / Common', hint: 'pǔ biàn' },
      { front: '个别', back: 'Individual / Specific', hint: 'gè bié' },
      { front: '整体', back: 'Whole / Entirety', hint: 'zhěng tǐ' },
      { front: '局部', back: 'Part / Local', hint: 'jú bù' },
      { front: '肯定', back: 'Affirmative / To confirm', hint: 'kěn dìng' },
      { front: '否定', back: 'Negative / To deny', hint: 'fǒu dìng' },
      { front: '表扬', back: 'Praise / To praise', hint: 'biǎo yáng' },
      { front: '经历', back: 'Experience / To experience', hint: 'jīng lì' },
      { front: '体验', back: 'Experience / To experience', hint: 'tǐ yàn' },
      { front: '困难', back: 'Difficulty / Trouble', hint: 'kùn nán' },
      { front: '危险', back: 'Danger / Dangerous', hint: 'wēi xiǎn' },
    ],
  },
]

const TOEIC_DECKS: DeckData[] = [
  {
    id: 'toeic-1-office',
    name: 'TOEIC 1 - Office Basics',
    description: 'Essential business English vocabulary for office communication',
    category: 'toeic',
    difficulty: 'beginner',
    language: 'english',
    deckIcon: 'english',
    tags: ['toeic', 'beginner', 'office', 'business'],
    cards: [
      { front: 'meeting', back: 'a formal gathering to discuss business', hint: '/ˈmiːtɪŋ/' },
      { front: 'schedule', back: 'a plan that lists times for activities', hint: '/ˈʃedjuːl/' },
      { front: 'deadline', back: 'the time by which something must be completed', hint: '/ˈdedlaɪn/' },
      { front: 'project', back: 'a planned piece of work', hint: '/ˈprɒdʒekt/' },
      { front: 'report', back: 'a written or spoken account of something', hint: '/rɪˈpɔːt/' },
      { front: 'email', back: 'a message sent electronically', hint: '/ˈiːmeɪl/' },
      { front: 'office', back: 'a room where business is conducted', hint: '/ˈɒfɪs/' },
      { front: 'department', back: 'a division of a company', hint: '/dɪˈpɑːtmənt/' },
      { front: 'colleague', back: 'a person with whom one works', hint: '/ˈkɒliːɡ/' },
      { front: 'manager', back: 'a person responsible for controlling an organization', hint: '/ˈmænɪdʒə/' },
      { front: 'employee', back: 'a person who works for a company', hint: '/ɪmˈplɔɪiː/' },
      { front: 'boss', back: 'the person in charge of a workplace', hint: '/bɒs/' },
      { front: 'client', back: 'a person or organization using services', hint: '/ˈklaɪənt/' },
      { front: 'customer', back: 'a person who buys goods or services', hint: '/ˈkʌstəmə/' },
      { front: 'appointment', back: 'a scheduled meeting', hint: '/əˈpɔɪntmənt/' },
      { front: 'conference', back: 'a large formal meeting', hint: '/ˈkɒnfərəns/' },
      { front: 'agenda', back: 'a list of items to be discussed', hint: '/əˈdʒendə/' },
      { front: 'minutes', back: 'a written record of a meeting', hint: '/ˈmɪnɪts/' },
      { front: 'presentation', back: 'a formal display of information', hint: '/ˌprezənˈteɪʃn/' },
      { front: 'document', back: 'an official paper or file', hint: '/ˈdɒkjumənt/' },
      { front: 'contract', back: 'a legal agreement', hint: '/ˈkɒntrækt/' },
      { front: 'invoice', back: 'a bill for goods or services', hint: '/ˈɪnvɔɪs/' },
      { front: 'receipt', back: 'proof of purchase', hint: '/rɪˈsiːt/' },
      { front: 'budget', back: 'an estimate of income and expenditure', hint: '/ˈbʌdʒɪt/' },
      { front: 'salary', back: 'a fixed regular payment', hint: '/ˈsæləri/' },
      { front: 'promotion', back: 'advancement in position or rank', hint: '/prəˈməʊʃn/' },
      { front: 'interview', back: 'a formal meeting for evaluation', hint: '/ˈɪntəvjuː/' },
      { front: 'resume', back: 'a summary of one\'s qualifications', hint: '/ˈrezjuːmeɪ/' },
      { front: 'training', back: 'the process of learning skills', hint: '/ˈtreɪnɪŋ/' },
      { front: 'computer', back: 'an electronic device for processing data', hint: '/kəmˈpjuːtə/' },
      { front: 'laptop', back: 'a portable computer', hint: '/ˈlæptɒp/' },
      { front: 'printer', back: 'a machine that produces printed copies', hint: '/ˈprɪntə/' },
      { front: 'software', back: 'computer programs', hint: '/ˈsɒftweə/' },
      { front: 'password', back: 'a secret word for access', hint: '/ˈpɑːswɜːd/' },
      { front: 'calendar', back: 'a system for tracking dates', hint: '/ˈkælɪndə/' },
      { front: 'task', back: 'a piece of work to be done', hint: '/tɑːsk/' },
      { front: 'goal', back: 'an aim or desired result', hint: '/ɡəʊl/' },
      { front: 'priority', back: 'something given special attention', hint: '/praɪˈɒrəti/' },
      { front: 'break', back: 'a period of rest', hint: '/breɪk/' },
      { front: 'lunch', back: 'a midday meal', hint: '/lʌntʃ/' },
      { front: 'vacation', back: 'a period of holiday', hint: '/vəˈkeɪʃn/' },
      { front: 'absent', back: 'not present', hint: '/ˈæbsənt/' },
      { front: 'available', back: 'able to be used or contacted', hint: '/əˈveɪləbl/' },
      { front: 'efficient', back: 'working well without waste', hint: '/ɪˈfɪʃnt/' },
      { front: 'professional', back: 'relating to one\'s profession', hint: '/prəˈfeʃənl/' },
      { front: 'confirm', back: 'to verify or establish definitely', hint: '/kənˈfɜːm/' },
      { front: 'cancel', back: 'to revoke or call off', hint: '/ˈkænsl/' },
      { front: 'reschedule', back: 'to change to another time', hint: '/riːˈʃedjuːl/' },
      { front: 'reply', back: 'to respond', hint: '/rɪˈplaɪ/' },
      { front: 'forward', back: 'to send on', hint: '/ˈfɔːwəd/' },
      { front: 'attach', back: 'to fasten or join', hint: '/əˈtætʃ/' },
      { front: 'copy', back: 'a reproduction', hint: '/ˈkɒpi/' },
      { front: 'fax', back: 'a system for sending documents', hint: '/fæks/' },
      { front: 'message', back: 'a verbal or written communication', hint: '/ˈmesɪdʒ/' },
      { front: 'note', back: 'a brief record', hint: '/nəʊt/' },
      { front: 'memo', back: 'a written message within an organization', hint: '/ˈmeməʊ/' },
      { front: 'letter', back: 'a written communication', hint: '/ˈletə/' },
      { front: 'sign', back: 'to write one\'s name', hint: '/saɪn/' },
      { front: 'stamp', back: 'an official mark or seal', hint: '/stæmp/' },
      { front: 'file', back: 'a folder or container for documents', hint: '/faɪl/' },
      { front: 'folder', back: 'a cover for holding papers', hint: '/ˈfəʊldə/' },
      { front: 'cabinet', back: 'a storage cupboard', hint: '/ˈkæbɪnət/' },
      { front: 'telephone', back: 'a device for speaking to others remotely', hint: '/ˈtelɪfəʊn/' },
      { front: 'call', back: 'a telephone connection', hint: '/kɔːl/' },
      { front: 'directory', back: 'a list of names and numbers', hint: '/dɪˈrektəri/' },
      { front: 'assist', back: 'to help', hint: '/əˈsɪst/' },
      { front: 'approve', back: 'to officially agree to', hint: '/əˈpruːv/' },
      { front: 'arrange', back: 'to organize or plan', hint: '/əˈreɪndʒ/' },
      { front: 'discuss', back: 'to talk about', hint: '/dɪˈskʌs/' },
      { front: 'explain', back: 'to make clear', hint: '/ɪkˈspleɪn/' },
      { front: 'prepare', back: 'to make ready', hint: '/prɪˈpeə/' },
      { front: 'complete', back: 'to finish', hint: '/kəmˈpliːt/' },
      { front: 'submit', back: 'to present for approval', hint: '/səbˈmɪt/' },
      { front: 'review', back: 'to examine critically', hint: '/rɪˈvjuː/' },
      { front: 'revise', back: 'to review and improve', hint: '/rɪˈvaɪz/' },
      { front: 'update', back: 'to make current', hint: '/ˌʌpˈdeɪt/' },
      { front: 'process', back: 'a series of actions', hint: '/ˈprəʊses/' },
      { front: 'handle', back: 'to manage or deal with', hint: '/ˈhændl/' },
      { front: 'coordinate', back: 'to organize harmoniously', hint: '/kəʊˈɔːdɪneɪt/' },
      { front: 'organize', back: 'to arrange systematically', hint: '/ˈɔːɡənaɪz/' },
      { front: 'implement', back: 'to put into effect', hint: '/ˈɪmplɪment/' },
      { front: 'maintain', back: 'to keep in good condition', hint: '/meɪnˈteɪn/' },
      { front: 'improve', back: 'to make better', hint: '/ɪmˈpruːv/' },
      { front: 'increase', back: 'to make greater', hint: '/ɪnˈkriːs/' },
      { front: 'decrease', back: 'to make smaller', hint: '/dɪˈkriːs/' },
      { front: 'reduce', back: 'to diminish', hint: '/rɪˈdjuːs/' },
      { front: 'expand', back: 'to increase in size', hint: '/ɪkˈspænd/' },
    ],
  },
  {
    id: 'toeic-2-business',
    name: 'TOEIC 2 - Business Communication',
    description: 'Vocabulary for meetings, negotiations, and professional correspondence',
    category: 'toeic',
    difficulty: 'intermediate',
    language: 'english',
    deckIcon: 'english',
    tags: ['toeic', 'intermediate', 'communication', 'business'],
    cards: [
      { front: 'negotiate', back: 'to discuss to reach an agreement', hint: '/nɪˈɡəʊʃieɪt/' },
      { front: 'proposal', back: 'a formal suggestion', hint: '/prəˈpəʊzl/' },
      { front: 'terms', back: 'conditions of an agreement', hint: '/tɜːmz/' },
      { front: 'agreement', back: 'a mutual arrangement', hint: '/əˈɡriːmənt/' },
      { front: 'negotiation', back: 'the process of negotiating', hint: '/nɪˌɡəʊʃiˈeɪʃn/' },
      { front: 'compromise', back: 'a middle ground between parties', hint: '/ˈkɒmprəmaɪz/' },
      { front: 'deal', back: 'a business transaction', hint: '/diːl/' },
      { front: 'offer', back: 'a proposed price or terms', hint: '/ˈɒfə/' },
      { front: 'accept', back: 'to agree to receive', hint: '/əkˈsept/' },
      { front: 'reject', back: 'to refuse to accept', hint: '/rɪˈdʒekt/' },
      { front: 'quotation', back: 'a formal estimate of price', hint: '/kwəʊˈteɪʃn/' },
      { front: 'discount', back: 'a reduction in price', hint: '/ˈdɪskaʊnt/' },
      { front: 'commission', back: 'a fee for services', hint: '/kəˈmɪʃn/' },
      { front: 'profit', back: 'financial gain', hint: '/ˈprɒfɪt/' },
      { front: 'loss', back: 'the opposite of profit', hint: '/lɒs/' },
      { front: 'revenue', back: 'income from business', hint: '/ˈrevənjuː/' },
      { front: 'expense', back: 'money spent', hint: '/ɪkˈspens/' },
      { front: 'investment', back: 'money put into business', hint: '/ɪnˈvestmənt/' },
      { front: 'shareholder', back: 'an owner of company shares', hint: '/ˈʃeəhəʊldə/' },
      { front: 'stock', back: 'shares in a company', hint: '/stɒk/' },
      { front: 'market', back: 'a place for buying and selling', hint: '/ˈmɑːkɪt/' },
      { front: 'competition', back: 'rivalry among businesses', hint: '/ˌkɒmpɪˈtɪʃn/' },
      { front: 'competitor', back: 'a rival company', hint: '/kəmˈpetɪtə/' },
      { front: 'strategy', back: 'a plan of action', hint: '/ˈstrætədʒi/' },
      { front: 'objective', back: 'a goal to be achieved', hint: '/əbˈdʒektɪv/' },
      { front: 'target', back: 'a goal to aim for', hint: '/ˈtɑːɡɪt/' },
      { front: 'achieve', back: 'to successfully accomplish', hint: '/əˈtʃiːv/' },
      { front: 'accomplish', back: 'to achieve or complete', hint: '/əˈkʌmplɪʃ/' },
      { front: 'benefit', back: 'an advantage or profit', hint: '/ˈbenɪfɪt/' },
      { front: 'opportunity', back: 'a favorable time or circumstance', hint: '/ˌɒpəˈtjuːnəti/' },
      { front: 'challenge', back: 'a difficult task or problem', hint: '/ˈtʃælɪndʒ/' },
      { front: 'obstacle', back: 'something that blocks progress', hint: '/ˈɒbstəkl/' },
      { front: 'solution', back: 'an answer to a problem', hint: '/səˈluːʃn/' },
      { front: 'issue', back: 'an important topic for discussion', hint: '/ˈɪʃuː/' },
      { front: 'concern', back: 'a matter of interest or worry', hint: '/kənˈsɜːn/' },
      { front: 'resolve', back: 'to find a solution to', hint: '/rɪˈzɒlv/' },
      { front: 'clarify', back: 'to make clear', hint: '/ˈklærɪfaɪ/' },
      { front: 'summarize', back: 'to give a brief statement', hint: '/ˈsʌməraɪz/' },
      { front: 'outline', back: 'the main points', hint: '/ˈaʊtlaɪn/' },
      { front: 'conclusion', back: 'the final part', hint: '/kənˈkluːʒn/' },
      { front: 'result', back: 'an outcome', hint: '/rɪˈzʌlt/' },
      { front: 'outcome', back: 'the way something turns out', hint: '/ˈaʊtkʌm/' },
      { front: 'consequence', back: 'a result of an action', hint: '/ˈkɒnsɪkwəns/' },
      { front: 'impact', back: 'a strong effect', hint: '/ˈɪmpækt/' },
      { front: 'affect', back: 'to influence', hint: '/əˈfekt/' },
      { front: 'influence', back: 'the power to affect', hint: '/ˈɪnfluəns/' },
      { front: 'effective', back: 'producing the desired result', hint: '/ɪˈfektɪv/' },
      { front: 'successful', back: 'achieving desired results', hint: '/səkˈsesfl/' },
      { front: 'productive', back: 'producing good results', hint: '/prəˈdʌktɪv/' },
      { front: 'reliable', back: 'able to be depended upon', hint: '/rɪˈlaɪəbl/' },
      { front: 'flexible', back: 'able to change easily', hint: '/ˈfleksəbl/' },
      { front: 'responsible', back: 'having a duty to do something', hint: '/rɪˈspɒnsəbl/' },
      { front: 'expert', back: 'a person with great knowledge', hint: '/ˈekspɜːt/' },
      { front: 'specialist', back: 'a person who specializes', hint: '/ˈspeʃəlɪst/' },
      { front: 'consultant', back: 'a professional advisor', hint: '/kənˈsʌltənt/' },
      { front: 'authority', back: 'the power to make decisions', hint: '/ɔːˈθɒrəti/' },
      { front: 'responsibility', back: 'a duty or obligation', hint: '/rɪˌspɒnsəˈbɪləti/' },
      { front: 'collaborate', back: 'to work together', hint: '/kəˈlæbəreɪt/' },
      { front: 'cooperate', back: 'to work together harmoniously', hint: '/kəʊˈɒpəreɪt/' },
      { front: 'partnership', back: 'a business relationship', hint: '/ˈpɑːtnəʃɪp/' },
      { front: 'acquire', back: 'to obtain or buy', hint: '/əˈkwaɪə/' },
      { front: 'merge', back: 'to combine into one', hint: '/mɜːdʒ/' },
      { front: 'relocate', back: 'to move to a new place', hint: '/ˌriːləˈkeɪt/' },
      { front: 'downsizing', back: 'reducing the number of employees', hint: '/ˈdaʊnsaɪzɪŋ/' },
      { front: 'restructure', back: 'to reorganize', hint: '/riːˈstrʌktʃə/' },
      { front: 'tactic', back: 'an action to achieve an aim', hint: '/ˈtæktɪk/' },
      { front: 'execute', back: 'to carry out', hint: '/ˈeksɪkjuːt/' },
      { front: 'delegate', back: 'to assign responsibility', hint: '/ˈdelɪɡeɪt/' },
      { front: 'authorize', back: 'to give official permission', hint: '/ˈɔːθəraɪz/' },
      { front: 'allocate', back: 'to distribute resources', hint: '/ˈæləkeɪt/' },
      { front: 'assess', back: 'to evaluate', hint: '/əˈses/' },
      { front: 'evaluate', back: 'to assess the value of', hint: '/ɪˈvæljueɪt/' },
      { front: 'estimate', back: 'to calculate approximately', hint: '/ˈestɪmət/' },
      { front: 'forecast', back: 'to predict future conditions', hint: '/ˈfɔːkɑːst/' },
      { front: 'anticipate', back: 'to expect or foresee', hint: '/ænˈtɪsɪpeɪt/' },
      { front: 'ensure', back: 'to make certain', hint: '/ɪnˈʃɔː/' },
      { front: 'guarantee', back: 'to promise', hint: '/ˌɡærənˈtiː/' },
      { front: 'verify', back: 'to confirm the truth', hint: '/ˈverɪfaɪ/' },
      { front: 'comply', back: 'to act in accordance with', hint: '/kəmˈplaɪ/' },
      { front: 'conform', back: 'to comply with rules', hint: '/kənˈfɔːm/' },
      { front: 'mandatory', back: 'required by law or rules', hint: '/ˈmændətəri/' },
      { front: 'regulation', back: 'a rule made by an authority', hint: '/ˌreɡjuˈleɪʃn/' },
    ],
  },
  {
    id: 'toeic-3-meetings',
    name: 'TOEIC 3 - Meetings & Presentations',
    description: 'Vocabulary for conducting effective meetings and presentations',
    category: 'toeic',
    difficulty: 'intermediate',
    language: 'english',
    deckIcon: 'english',
    tags: ['toeic', 'intermediate', 'meeting', 'presentation'],
    cards: [
      { front: 'chairperson', back: 'the person leading a meeting', hint: '/ˈtʃeəpɜːsn/' },
      { front: 'facilitator', back: 'a person who helps a meeting run smoothly', hint: '/fəˈsɪlɪteɪtə/' },
      { front: 'attendee', back: 'a person present at a meeting', hint: '/əˌtenˈdiː/' },
      { front: 'participant', back: 'a person taking part in an activity', hint: '/pɑːˈtɪsɪpənt/' },
      { front: 'quorum', back: 'the minimum number needed for a meeting', hint: '/ˈkwɔːrəm/' },
      { front: 'item', back: 'a single item on an agenda', hint: '/ˈaɪtəm/' },
      { front: 'discussion', back: 'conversation about a topic', hint: '/dɪˈskʌʃn/' },
      { front: 'debate', back: 'a formal discussion', hint: '/dɪˈbeɪt/' },
      { front: 'brainstorm', back: 'to generate ideas freely', hint: '/ˈbreɪnstɔːm/' },
      { front: 'consensus', back: 'general agreement', hint: '/kənˈsensəs/' },
      { front: 'decision', back: 'a conclusion reached', hint: '/dɪˈsɪʒn/' },
      { front: 'vote', back: 'to formally indicate a choice', hint: '/vəʊt/' },
      { front: 'motion', back: 'a formal proposal for discussion', hint: '/ˈməʊʃn/' },
      { front: 'propose', back: 'to put forward for consideration', hint: '/prəˈpəʊz/' },
      { front: 'second', back: 'to support a proposal', hint: '/ˈsekənd/' },
      { front: 'amend', back: 'to make changes to', hint: '/əˈmend/' },
      { front: 'table', back: 'to postpone discussion', hint: '/ˈteɪbl/' },
      { front: 'adjourn', back: 'to temporarily stop a meeting', hint: '/əˈdʒɜːn/' },
      { front: 'record', back: 'to document', hint: '/ˈrekɔːd/' },
      { front: 'action item', back: 'a task assigned during a meeting', hint: '/ˈækʃn ˈaɪtəm/' },
      { front: 'follow up', back: 'to continue or check on', hint: '/ˈfɒləʊ ʌp/' },
      { front: 'deliver', back: 'to give a presentation', hint: '/dɪˈlɪvə/' },
      { front: 'audience', back: 'the people watching or listening', hint: '/ˈɔːdiəns/' },
      { front: 'slide', back: 'a page in a presentation', hint: '/slaɪd/' },
      { front: 'visual aid', back: 'a chart, graph, or image', hint: '/ˈvɪʒuəl eɪd/' },
      { front: 'handout', back: 'printed material for audience', hint: '/ˈhændaʊt/' },
      { front: 'projector', back: 'a device for displaying images', hint: '/prəˈdʒektə/' },
      { front: 'microphone', back: 'a device for amplifying voice', hint: '/ˈmaɪkrəfəʊn/' },
      { front: 'introduce', back: 'to present for the first time', hint: '/ˌɪntrəˈdjuːs/' },
      { front: 'present', back: 'to formally give information', hint: '/prɪˈzent/' },
      { front: 'demonstrate', back: 'to show how something works', hint: '/ˈdemənstreɪt/' },
      { front: 'illustrate', back: 'to explain with examples', hint: '/ˈɪləstreɪt/' },
      { front: 'elaborate', back: 'to give more details', hint: '/ɪˈlæbəreɪt/' },
      { front: 'emphasize', back: 'to give special importance to', hint: '/ˈemfəsaɪz/' },
      { front: 'highlight', back: 'to emphasize important points', hint: '/ˈhaɪlaɪt/' },
      { front: 'reiterate', back: 'to repeat for emphasis', hint: '/riːˈɪtəreɪt/' },
      { front: 'describe', back: 'to give details about', hint: '/dɪˈskraɪb/' },
      { front: 'compare', back: 'to examine similarities', hint: '/kəmˈpeə/' },
      { front: 'contrast', back: 'to show differences', hint: '/kənˈtrɑːst/' },
      { front: 'analyze', back: 'to examine in detail', hint: '/ˈænəlaɪz/' },
      { front: 'recommend', back: 'to suggest favorably', hint: '/ˌrekəˈmend/' },
      { front: 'suggest', back: 'to put forward an idea', hint: '/səˈdʒest/' },
      { front: 'recommendation', back: 'a suggestion or advice', hint: '/ˌrekəmenˈdeɪʃn/' },
      { front: 'finding', back: 'information discovered', hint: '/ˈfaɪndɪŋ/' },
      { front: 'feedback', back: 'comments on performance', hint: '/ˈfiːdbæk/' },
      { front: 'comment', back: 'a remark or observation', hint: '/ˈkɒment/' },
      { front: 'question', back: 'to ask for information', hint: '/ˈkwestʃən/' },
      { front: 'inquiry', back: 'a question or investigation', hint: '/ɪnˈkwaɪəri/' },
      { front: 'clarification', back: 'an explanation that makes things clear', hint: '/ˌklærɪfɪˈkeɪʃn/' },
      { front: 'justification', back: 'a reason for doing something', hint: '/ˌdʒʌstɪfɪˈkeɪʃn/' },
      { front: 'objection', back: 'an expression of disapproval', hint: '/əbˈdʒekʃn/' },
      { front: 'alternative', back: 'something available as another choice', hint: '/ɔːlˈtɜːnətɪv/' },
      { front: 'option', back: 'a choice', hint: '/ˈɒpʃn/' },
      { front: 'preference', back: 'a greater liking for one thing over another', hint: '/ˈprefərəns/' },
      { front: 'significant', back: 'important or large enough to have an effect', hint: '/sɪɡˈnɪfɪkənt/' },
      { front: 'substantial', back: 'large in amount or important', hint: '/səbˈstænʃl/' },
      { front: 'relevant', back: 'closely connected to the matter', hint: '/ˈreləvənt/' },
      { front: 'insightful', back: 'showing a clear understanding', hint: '/ˈɪnsaɪtfʊl/' },
      { front: 'persuasive', back: 'able to convince others', hint: '/pəˈsweɪsɪv/' },
      { front: 'compelling', back: 'very convincing', hint: '/kəmˈpelɪŋ/' },
      { front: 'briefing', back: 'a meeting to give instructions or information', hint: '/ˈbriːfɪŋ/' },
      { front: 'workshop', back: 'a meeting for intensive discussion', hint: '/ˈwɜːkʃɒp/' },
      { front: 'seminar', back: 'a class or meeting for study', hint: '/ˈsemɪnɑː/' },
      { front: 'symposium', back: 'a conference for discussion', hint: '/sɪmˈpəʊziəm/' },
      { front: 'forum', back: 'a place for open discussion', hint: '/ˈfɔːrəm/' },
      { front: 'panel', back: 'a group of experts discussing', hint: '/ˈpænl/' },
      { front: 'roundtable', back: 'an informal meeting of equals', hint: '/ˈraʊndteɪbl/' },
    ],
  },
  {
    id: 'toeic-4-finance',
    name: 'TOEIC 4 - Finance & Marketing',
    description: 'Vocabulary for financial documents, transactions, and marketing activities',
    category: 'toeic',
    difficulty: 'advanced',
    language: 'english',
    deckIcon: 'english',
    tags: ['toeic', 'advanced', 'finance', 'marketing'],
    cards: [
      { front: 'balance sheet', back: 'a statement of assets and liabilities', hint: '/ˈbæləns ʃiːt/' },
      { front: 'income statement', back: 'a record of revenues and expenses', hint: '/ˈɪnkʌm ˈsteɪtmənt/' },
      { front: 'assets', back: 'resources owned by a business', hint: '/ˈæsets/' },
      { front: 'liabilities', back: 'debts or obligations', hint: '/ˌlaɪəˈbɪlətiz/' },
      { front: 'equity', back: 'the value of ownership', hint: '/ˈekwəti/' },
      { front: 'capital', back: 'wealth used for investment', hint: '/ˈkæpɪtl/' },
      { front: 'gross profit', back: 'profit before expenses', hint: '/ɡrəʊs ˈprɒfɪt/' },
      { front: 'net profit', back: 'profit after all expenses', hint: '/net ˈprɒfɪt/' },
      { front: 'turnover', back: 'the total sales of a business', hint: '/ˈtɜːnˌəʊvə/' },
      { front: 'cash flow', back: 'the movement of money in and out', hint: '/kæʃ fləʊ/' },
      { front: 'liquidity', back: 'the ease of converting to cash', hint: '/lɪˈkwɪdəti/' },
      { front: 'depreciation', back: 'decrease in value over time', hint: '/dɪˌpriːʃiˈeɪʃn/' },
      { front: 'audit', back: 'an official examination of accounts', hint: '/ˈɔːdɪt/' },
      { front: 'fiscal year', back: 'a 12-month accounting period', hint: '/ˈfɪskl jɪə/' },
      { front: 'quarterly', back: 'done every three months', hint: '/ˈkwɔːtəli/' },
      { front: 'dividend', back: 'a share of profits paid to shareholders', hint: '/ˈdɪvɪdend/' },
      { front: 'share', back: 'a unit of ownership in a company', hint: '/ʃeə/' },
      { front: 'bond', back: 'a fixed-income investment', hint: '/bɒnd/' },
      { front: 'portfolio', back: 'a collection of investments', hint: '/pɔːtˈfəʊliəʊ/' },
      { front: 'diversify', back: 'to spread investments across areas', hint: '/daɪˈvɜːsɪfaɪ/' },
      { front: 'interest rate', back: 'the cost of borrowing money', hint: '/ˈɪntrəst reɪt/' },
      { front: 'inflation', back: 'a general increase in prices', hint: '/ɪnˈfleɪʃn/' },
      { front: 'currency', back: 'the money system of a country', hint: '/ˈkʌrənsi/' },
      { front: 'exchange rate', back: 'the value of one currency compared to another', hint: '/ɪksˈtʃeɪndʒ reɪt/' },
      { front: 'transaction', back: 'a business deal or action', hint: '/trænˈzækʃn/' },
      { front: 'transfer', back: 'to move money between accounts', hint: '/trænsˈfɜː/' },
      { front: 'deposit', back: 'money placed in a bank', hint: '/dɪˈpɒzɪt/' },
      { front: 'withdrawal', back: 'the act of taking money out', hint: '/wɪðˈdrɔːəl/' },
      { front: 'collateral', back: 'security offered for a loan', hint: '/kəˈlætərəl/' },
      { front: 'mortgage', back: 'a loan for property', hint: '/ˈmɔːɡɪdʒ/' },
      { front: 'overdraft', back: 'borrowing beyond available funds', hint: '/ˈəʊvədrɑːft/' },
      { front: 'credit', back: 'the ability to borrow', hint: '/ˈkredɪt/' },
      { front: 'bankruptcy', back: 'the state of being unable to pay debts', hint: '/ˈbæŋkrəptsi/' },
      { front: 'merger', back: 'when two companies combine', hint: '/ˈmɜːdʒə/' },
      { front: 'acquisition', back: 'the purchase of one company by another', hint: '/ˌækwɪˈzɪʃn/' },
      { front: 'headquarters', back: 'the main office', hint: '/ˌhedˈkwɔːtəz/' },
      { front: 'franchise', back: 'a business given rights to operate', hint: '/ˈfræntʃaɪz/' },
      { front: 'retail', back: 'sale of goods to consumers', hint: '/ˈriːteɪl/' },
      { front: 'wholesale', back: 'sale of goods in bulk', hint: '/ˈhəʊlseɪl/' },
      { front: 'distribution', back: 'the process of delivering products', hint: '/ˌdɪstrɪˈbjuːʃn/' },
      { front: 'logistics', back: 'the management of movement of goods', hint: '/ləˈdʒɪstɪks/' },
      { front: 'inventory', back: 'goods held for sale', hint: '/ˈɪnvəntri/' },
      { front: 'shipment', back: 'goods sent together', hint: '/ˈʃɪpmənt/' },
      { front: 'delivery', back: 'the act of bringing goods', hint: '/dɪˈlɪvəri/' },
      { front: 'supplier', back: 'a company that provides goods', hint: '/səˈplaɪə/' },
      { front: 'vendor', back: 'a seller', hint: '/ˈvendə/' },
      { front: 'manufacturer', back: 'a company that makes products', hint: '/ˌmænjuˈfæktʃərə/' },
      { front: 'advertising', back: 'the promotion of products', hint: '/ˈædvətaɪzɪŋ/' },
      { front: 'campaign', back: 'a planned marketing effort', hint: '/kæmˈpeɪn/' },
      { front: 'branding', back: 'creating an identity for a product', hint: '/ˈbrændɪŋ/' },
      { front: 'target market', back: 'the specific group of consumers', hint: '/ˈtɑːɡɪt ˈmɑːkɪt/' },
      { front: 'demographic', back: 'a statistical group of people', hint: '/ˌdeməˈɡræfɪk/' },
      { front: 'segment', back: 'a part of a market', hint: '/ˈsegmənt/' },
      { front: 'launch', back: 'to introduce a new product', hint: '/lɔːntʃ/' },
      { front: 'promotion', back: 'activities to increase sales', hint: '/prəˈməʊʃn/' },
      { front: 'coupon', back: 'a voucher for a discount', hint: '/ˈkuːpɒn/' },
      { front: 'sponsorship', back: 'financial support for an event', hint: '/ˈspɒnsəʃɪp/' },
      { front: 'survey', back: 'a study of opinions or behaviors', hint: '/ˈsɜːveɪ/' },
      { front: 'market research', back: 'the study of market conditions', hint: '/ˈmɑːkɪt rɪˈsɜːtʃ/' },
      { front: 'feasibility', back: 'the possibility of being done', hint: '/ˌfiːzəˈbɪləti/' },
      { front: 'ROI', back: 'return on investment', hint: '/ˌɑːr əʊ ˈaɪ/' },
      { front: 'profit margin', back: 'the percentage of profit from revenue', hint: '/ˈprɒfɪt ˈmɑːdʒɪn/' },
      { front: 'market share', back: 'the portion of a market controlled', hint: '/ˈmɑːkɪt ʃeə/' },
      { front: 'brand awareness', back: 'how well people know a brand', hint: '/brænd əˈweənəs/' },
      { front: 'customer loyalty', back: 'a customer\'s commitment to a brand', hint: '/ˈkʌstəmə ˈlɔɪəlti/' },
      { front: 'conversion rate', back: 'the percentage of visitors who buy', hint: '/kənˈvɜːʒn reɪt/' },
      { front: 'lead', back: 'a potential customer', hint: '/liːd/' },
      { front: 'prospect', back: 'a potential client', hint: '/ˈprɒspekt/' },
      { front: 'pipeline', back: 'potential future business', hint: '/ˈpaɪplaɪn/' },
      { front: 'closing', back: 'finalizing a sale', hint: '/ˈkləʊzɪŋ/' },
      { front: 'proposal', back: 'a formal suggestion', hint: '/prəˈpəʊzl/' },
      { front: 'payment', back: 'money given for goods or services', hint: '/ˈpeɪmənt/' },
      { front: 'installment', back: 'a part of a payment spread over time', hint: '/ɪnˈstɔːlmənt/' },
      { front: 'refund', back: 'money returned to a customer', hint: '/ˈriːfʌnd/' },
      { front: 'warranty', back: 'a guarantee for a product', hint: '/ˈwɒrənti/' },
    ],
  },
  {
    id: 'toeic-5-legal-hr',
    name: 'TOEIC 5 - Legal & Human Resources',
    description: 'Advanced vocabulary for legal documents, employment, and HR matters',
    category: 'toeic',
    difficulty: 'advanced',
    language: 'english',
    deckIcon: 'english',
    tags: ['toeic', 'advanced', 'legal', 'hr'],
    cards: [
      { front: 'contract', back: 'a legally binding agreement', hint: '/ˈkɒntrækt/' },
      { front: 'obligation', back: 'a duty or commitment', hint: '/ˌɒblɪˈɡeɪʃn/' },
      { front: 'liability', back: 'legal responsibility', hint: '/ˌlaɪəˈbɪləti/' },
      { front: 'breach', back: 'a violation of a contract', hint: '/briːtʃ/' },
      { front: 'violation', back: 'an act of breaking a rule', hint: '/ˌvaɪəˈleɪʃn/' },
      { front: 'termination', back: 'the act of ending', hint: '/ˌtɜːmɪˈneɪʃn/' },
      { front: 'resignation', back: 'voluntary departure from a job', hint: '/ˌreɡɪɡˈneɪʃn/' },
      { front: 'dismissal', back: 'the act of firing an employee', hint: '/dɪsˈmɪsl/' },
      { front: 'layoff', back: 'temporary unemployment due to business reasons', hint: '/ˈleɪɒf/' },
      { front: 'severance', back: 'payment upon termination', hint: '/ˈsevərəns/' },
      { front: 'compensation', back: 'payment for work or injury', hint: '/ˌkɒmpenˈseɪʃn/' },
      { front: 'bonus', back: 'extra payment as a reward', hint: '/ˈbəʊnəs/' },
      { front: 'allowance', back: 'money given regularly for expenses', hint: '/əˈlaʊəns/' },
      { front: 'benefits', back: 'non-wage compensation', hint: '/ˈbenɪfɪts/' },
      { front: 'perks', back: 'extra benefits from employment', hint: '/pɜːks/' },
      { front: 'insurance', back: 'protection against financial loss', hint: '/ɪnˈʊərəns/' },
      { front: 'pension', back: 'retirement fund', hint: '/ˈpenʃn/' },
      { front: 'procedure', back: 'a series of actions for a task', hint: '/prəˈsiːdʒə/' },
      { front: 'protocol', back: 'a code of conduct', hint: '/ˈprəʊtəkɒl/' },
      { front: 'non-compliance', back: 'failure to follow rules', hint: '/nɒn kəmˈplaɪəns/' },
      { front: 'confidential', back: 'intended to be kept secret', hint: '/ˌkɒnfɪˈdenʃl/' },
      { front: 'disclosure', back: 'the act of making information known', hint: '/dɪsˈkləʊʒə/' },
      { front: 'dispute', back: 'a disagreement', hint: '/dɪˈspjuːt/' },
      { front: 'arbitration', back: 'resolution of dispute by a third party', hint: '/ˌɑːbɪˈtreɪʃn/' },
      { front: 'mediation', back: 'assistance in resolving a dispute', hint: '/ˌmiːdiˈeɪʃn/' },
      { front: 'litigation', back: 'legal proceedings', hint: '/ˌlɪtɪˈɡeɪʃn/' },
      { front: 'lawsuit', back: 'a legal action', hint: '/ˈlɔːsuːt/' },
      { front: 'claim', back: 'a demand for something due', hint: '/kleɪm/' },
      { front: 'settlement', back: 'an agreement to resolve a dispute', hint: '/ˈsetlmənt/' },
      { front: 'damages', back: 'money awarded for harm', hint: '/ˈdæmɪdʒɪz/' },
      { front: 'jurisdiction', back: 'the authority to make legal decisions', hint: '/ˌdʒʊərɪsˈdɪkʃn/' },
      { front: 'testimony', back: 'a formal statement in court', hint: '/ˈtestɪməni/' },
      { front: 'evidence', back: 'proof presented in court', hint: '/ˈevɪdəns/' },
      { front: 'witness', back: 'a person who testifies', hint: '/ˈwɪtnəs/' },
      { front: 'defendant', back: 'the person accused', hint: '/dɪˈfendənt/' },
      { front: 'plaintiff', back: 'the person who sues', hint: '/ˈpleɪntɪf/' },
      { front: 'attorney', back: 'a lawyer', hint: '/əˈtɜːni/' },
      { front: 'verdict', back: 'the decision of a jury or judge', hint: '/ˈvɜːdɪkt/' },
      { front: 'intellectual property', back: 'creations of the mind', hint: '/ˌɪntəˈlektʃuəl ˈprɒpəti/' },
      { front: 'patent', back: 'exclusive rights to an invention', hint: '/ˈpætnt/' },
      { front: 'trademark', back: 'a symbol of a company', hint: '/ˈtreɪdmɑːk/' },
      { front: 'copyright', back: 'legal right to control a work', hint: '/ˈkɒpiraɪt/' },
      { front: 'license', back: 'official permission to use', hint: '/ˈlaɪsns/' },
      { front: 'recruitment', back: 'the process of hiring', hint: '/rɪˈkruːtmənt/' },
      { front: 'screening', back: 'the process of evaluating candidates', hint: '/ˈskriːnɪŋ/' },
      { front: 'shortlist', back: 'a list of preferred candidates', hint: '/ˈʃɔːtlɪst/' },
      { front: 'assessment', back: 'evaluation', hint: '/əˈsesmənt/' },
      { front: 'appraisal', back: 'a formal evaluation of performance', hint: '/əˈpreɪzl/' },
      { front: 'probation', back: 'a trial period of employment', hint: '/prəˈbeɪʃn/' },
      { front: 'induction', back: 'the process of introducing a new employee', hint: '/ɪnˈdʌkʃn/' },
      { front: 'orientation', back: 'training for new employees', hint: '/ˌɔːriənˈteɪʃn/' },
      { front: 'onboarding', back: 'the process of integrating new hires', hint: '/ˈɒnbɔːdɪŋ/' },
      { front: 'coaching', back: 'guidance for improvement', hint: '/ˈkəʊtʃɪŋ/' },
      { front: 'mentoring', back: 'advice from an experienced person', hint: '/ˈmentərɪŋ/' },
      { front: 'productivity', back: 'the efficiency of production', hint: '/ˌprɒdʌkˈtɪvəti/' },
      { front: 'morale', back: 'the emotional state of a group', hint: '/məˈrɑːl/' },
      { front: 'turnover', back: 'the rate at which employees leave', hint: '/ˈtɜːnˌəʊvə/' },
      { front: 'retention', back: 'keeping employees', hint: '/rɪˈtenʃn/' },
      { front: 'succession', back: 'the process of replacing someone', hint: '/səkˈseʃn/' },
      { front: 'redundancy', back: 'the state of being unemployed due to fewer jobs', hint: '/rɪˈdʌndənsi/' },
      { front: 'outsourcing', back: 'contracting work to another company', hint: '/ˈaʊtsɔːsɪŋ/' },
      { front: 'offshoring', back: 'moving jobs to another country', hint: '/ˈɒfˌʃɔːrɪŋ/' },
      { front: 'labor union', back: 'an organization representing workers', hint: '/ˈleɪbə juːnjən/' },
      { front: 'collective bargaining', back: 'negotiation with unions', hint: '/kəˈlektɪv ˈbɑːɡɪnɪŋ/' },
      { front: 'strike', back: 'a work stoppage by employees', hint: '/straɪk/' },
      { front: 'harassment', back: 'behavior that annoys or threatens', hint: '/ˈhærəsmənt/' },
      { front: 'discrimination', back: 'unfair treatment based on characteristics', hint: '/dɪˌskrɪmɪˈneɪʃn/' },
      { front: 'equality', back: 'the state of being equal', hint: '/iːˈkwɒləti/' },
      { front: 'diversity', back: 'the inclusion of different types of people', hint: '/daɪˈvɜːsəti/' },
      { front: 'inclusion', back: 'the practice of including people', hint: '/ɪnˈkluːʒn/' },
    ],
  },
]

const GENERAL_DECKS: DeckData[] = [
  {
    id: 'general-english',
    name: 'English Vocabulary',
    description: 'Essential words for everyday use',
    category: 'general',
    difficulty: 'beginner',
    language: 'english',
    deckIcon: 'general',
    tags: ['english', 'beginner', 'vocabulary'],
    cards: [
      { front: 'Hello', back: 'A greeting used when meeting someone', hint: 'Common greeting' },
      { front: 'Thank you', back: 'An expression of gratitude', hint: 'Showing appreciation' },
      { front: 'Please', back: 'Used to add politeness to a request', hint: 'Being courteous' },
      { front: 'Goodbye', back: 'A farewell when parting', hint: 'Parting words' },
      { front: 'Welcome', back: 'A greeting to receive someone', hint: 'Hospitality' },
      { front: 'Sorry', back: 'An expression of apology', hint: 'Showing regret' },
      { front: 'Help', back: 'Assistance or support', hint: 'Offering aid' },
      { front: 'Water', back: 'A clear liquid for drinking', hint: 'H2O' },
      { front: 'Food', back: 'Something to eat', hint: 'Nutrition' },
      { front: 'House', back: 'A building for living', hint: 'Home' },
      { front: 'Car', back: 'A vehicle with four wheels', hint: 'Transportation' },
      { front: 'Book', back: 'A written or printed work', hint: 'Reading material' },
      { front: 'Phone', back: 'A device for communication', hint: 'Mobile device' },
      { front: 'Time', back: 'The ongoing sequence of events', hint: 'Clock' },
      { front: 'Day', back: 'A period of 24 hours', hint: 'Daytime' },
      { front: 'Night', back: 'The period of darkness', hint: 'Evening hours' },
      { front: 'Morning', back: 'The early part of the day', hint: 'AM hours' },
      { front: 'Evening', back: 'The later part of the afternoon', hint: 'PM hours' },
      { front: 'Friend', back: 'A person you know well', hint: 'Companion' },
      { front: 'Family', back: 'People related by blood or marriage', hint: 'Relatives' },
      { front: 'Work', back: 'A job or occupation', hint: 'Employment' },
      { front: 'School', back: 'A place for education', hint: 'Learning' },
      { front: 'Money', back: 'A medium of exchange', hint: 'Currency' },
      { front: 'Bank', back: 'A place for keeping money', hint: 'Financial institution' },
      { front: 'Store', back: 'A place where goods are sold', hint: 'Shop' },
      { front: 'Hospital', back: 'A place for medical care', hint: 'Healthcare' },
      { front: 'Doctor', back: 'A medical professional', hint: 'Physician' },
      { front: 'Medicine', back: 'A treatment for illness', hint: 'Medication' },
      { front: 'Happy', back: 'Feeling joy', hint: 'Joyful' },
      { front: 'Sad', back: 'Feeling sorrow', hint: 'Unhappy' },
      { front: 'Angry', back: 'Feeling rage', hint: 'Mad' },
      { front: 'Tired', back: 'Needing rest', hint: 'Exhausted' },
      { front: 'Hungry', back: 'Needing food', hint: 'Starving' },
      { front: 'Thirsty', back: 'Needing a drink', hint: 'Dry' },
      { front: 'Beautiful', back: 'Pleasing to look at', hint: 'Pretty' },
      { front: 'Ugly', back: 'Unpleasant to look at', hint: 'Unattractive' },
      { front: 'Big', back: 'Large in size', hint: 'Huge' },
      { front: 'Small', back: 'Little in size', hint: 'Tiny' },
      { front: 'Hot', back: 'High temperature', hint: 'Warm' },
      { front: 'Cold', back: 'Low temperature', hint: 'Cool' },
      { front: 'Fast', back: 'Quick in speed', hint: 'Rapid' },
      { front: 'Slow', back: 'Not fast', hint: 'Sluggish' },
      { front: 'Easy', back: 'Not difficult', hint: 'Simple' },
      { front: 'Difficult', back: 'Hard to do', hint: 'Challenging' },
      { front: 'New', back: 'Recently made', hint: 'Fresh' },
      { front: 'Old', back: 'Not new', hint: 'Aged' },
      { front: 'Good', back: 'Positive quality', hint: 'Great' },
      { front: 'Bad', back: 'Negative quality', hint: 'Poor' },
      { front: 'Right', back: 'Correct or opposite of left', hint: 'Correct' },
      { front: 'Left', back: 'Opposite of right', hint: 'Left side' },
      { front: 'Up', back: 'Moving to a higher position', hint: 'Above' },
      { front: 'Down', back: 'Moving to a lower position', hint: 'Below' },
      { front: 'In', back: 'Inside', hint: 'Within' },
      { front: 'Out', back: 'Outside', hint: 'Exit' },
      { front: 'Come', back: 'To arrive at a place', hint: 'Approach' },
      { front: 'Go', back: 'To move away', hint: 'Leave' },
      { front: 'Eat', back: 'To consume food', hint: 'Dine' },
      { front: 'Drink', back: 'To consume liquid', hint: 'Sip' },
      { front: 'Sleep', back: 'To rest with eyes closed', hint: 'Rest' },
      { front: 'Wake', back: 'To stop sleeping', hint: 'Awaken' },
      { front: 'Walk', back: 'To move on foot', hint: 'Step' },
      { front: 'Run', back: 'To move quickly on foot', hint: 'Sprint' },
      { front: 'Read', back: 'To look at written words', hint: 'Study' },
      { front: 'Write', back: 'To form letters or words', hint: 'Pen' },
      { front: 'Speak', back: 'To say words', hint: 'Talk' },
      { front: 'Listen', back: 'To hear with attention', hint: 'Hear' },
      { front: 'See', back: 'To use your eyes', hint: 'Look' },
      { front: 'Think', back: 'To use your mind', hint: 'Consider' },
    ],
  },
  {
    id: 'general-math',
    name: 'Math Basics',
    description: 'Simple arithmetic and concepts',
    category: 'general',
    difficulty: 'beginner',
    language: 'general',
    deckIcon: 'general',
    tags: ['math', 'beginner', 'arithmetic'],
    cards: [
      { front: '2 + 2 = ?', back: '4', hint: 'Basic addition' },
      { front: '5 × 3 = ?', back: '15', hint: 'Multiplication' },
      { front: '10 - 7 = ?', back: '3', hint: 'Subtraction' },
      { front: '16 ÷ 4 = ?', back: '4', hint: 'Division' },
      { front: '7 + 8 = ?', back: '15', hint: 'Sum' },
      { front: '9 × 9 = ?', back: '81', hint: 'Square' },
      { front: '100 - 37 = ?', back: '63', hint: 'Difference' },
      { front: '144 ÷ 12 = ?', back: '12', hint: 'Division' },
      { front: '25 + 17 = ?', back: '42', hint: 'Sum' },
      { front: '8 × 7 = ?', back: '56', hint: 'Product' },
      { front: '50 - 23 = ?', back: '27', hint: 'Remainder' },
      { front: '20 × 5 = ?', back: '100', hint: 'Multiple of 5' },
      { front: '99 ÷ 9 = ?', back: '11', hint: 'Divisible' },
      { front: '6 + 9 + 3 = ?', back: '18', hint: 'Sum of three' },
      { front: '15 - 8 = ?', back: '7', hint: 'Take away' },
      { front: '11 × 11 = ?', back: '121', hint: 'Square' },
      { front: '200 + 300 = ?', back: '500', hint: 'Adding hundreds' },
      { front: '45 ÷ 5 = ?', back: '9', hint: 'Divisible by 5' },
      { front: '14 + 28 = ?', back: '42', hint: 'Even numbers' },
      { front: '9 × 6 = ?', back: '54', hint: 'Product' },
    ],
  },
  {
    id: 'general-capitals',
    name: 'World Capitals',
    description: 'Learn the capitals of major countries',
    category: 'general',
    difficulty: 'beginner',
    language: 'general',
    deckIcon: 'globe',
    tags: ['geography', 'beginner', 'capitals'],
    cards: [
      { front: 'France', back: 'Paris', hint: 'Western Europe' },
      { front: 'Japan', back: 'Tokyo', hint: 'East Asia' },
      { front: 'Australia', back: 'Canberra', hint: 'Oceania' },
      { front: 'Brazil', back: 'Brasília', hint: 'South America' },
      { front: 'Canada', back: 'Ottawa', hint: 'North America' },
      { front: 'Germany', back: 'Berlin', hint: 'Central Europe' },
      { front: 'Italy', back: 'Rome', hint: 'Southern Europe' },
      { front: 'Spain', back: 'Madrid', hint: 'Iberian Peninsula' },
      { front: 'United Kingdom', back: 'London', hint: 'British Isles' },
      { front: 'United States', back: 'Washington D.C.', hint: 'North America' },
      { front: 'China', back: 'Beijing', hint: 'East Asia' },
      { front: 'South Korea', back: 'Seoul', hint: 'East Asia' },
      { front: 'India', back: 'New Delhi', hint: 'South Asia' },
      { front: 'Russia', back: 'Moscow', hint: 'Eastern Europe' },
      { front: 'Mexico', back: 'Mexico City', hint: 'North America' },
      { front: 'Argentina', back: 'Buenos Aires', hint: 'South America' },
      { front: 'Egypt', back: 'Cairo', hint: 'North Africa' },
      { front: 'South Africa', back: 'Pretoria', hint: 'Southern Africa' },
      { front: 'Thailand', back: 'Bangkok', hint: 'Southeast Asia' },
      { front: 'Vietnam', back: 'Hanoi', hint: 'Southeast Asia' },
      { front: 'Indonesia', back: 'Jakarta', hint: 'Southeast Asia' },
      { front: 'Turkey', back: 'Ankara', hint: 'Western Asia' },
      { front: 'Saudi Arabia', back: 'Riyadh', hint: 'Middle East' },
      { front: 'Poland', back: 'Warsaw', hint: 'Central Europe' },
      { front: 'Netherlands', back: 'Amsterdam', hint: 'Western Europe' },
    ],
  },
]

async function seedSystemUser() {
  console.log('Seeding system user...')
  
  const hashedPassword = await bcrypt.hash('system-password-do-not-use', 10)
  
  await db.insert(users).values({
    id: SYSTEM_USER_ID,
    email: 'system@flashlearn.local',
    name: 'FlashLearn System',
    password: hashedPassword,
    phone: null,
    emailVerifiedAt: null,
    rememberToken: null,
    isAdmin: '0',
    turnUsed: 0,
    turnRemaining: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }).onConflictDoNothing()
  
  console.log('✓ System user seeded')
}

async function seedDecksAndCards() {
  const allDecks = [...HSK_DECKS, ...TOEIC_DECKS, ...GENERAL_DECKS]
  
  console.log(`Seeding ${allDecks.length} decks...`)
  
  for (const deckData of allDecks) {
    const existingDeck = await db.query.decks.findFirst({
      where: (decks, { eq }) => eq(decks.id, deckData.id),
    })
    
    if (existingDeck) {
      console.log(`  - ${deckData.name} (already exists, skipping)`)
      continue
    }
    
    const deckId = deckData.id
    
    await db.insert(decks).values({
      id: deckId,
      userId: SYSTEM_USER_ID,
      name: deckData.name,
      description: deckData.description,
      category: deckData.category as any,
      difficulty: deckData.difficulty as any,
      language: deckData.language as any,
      isPreBuilt: true,
      deckIcon: deckData.deckIcon,
      tags: deckData.tags,
      version: '1.0.0',
      createdAt: new Date(),
    })
    
    const cardsToInsert = deckData.cards.map((card, index) => ({
      id: uuidv4(),
      deckId: deckId,
      front: card.front,
      back: card.back,
      hint: card.hint || null,
      reviewCount: 0,
      createdAt: new Date(),
    }))
    
    await db.insert(cards).values(cardsToInsert)
    
    console.log(`  - ${deckData.name} (${deckData.cards.length} cards)`)
  }
}

async function main() {
  console.log('Starting pre-built decks seed...\n')
  
  try {
    await seedSystemUser()
    await seedDecksAndCards()
    
    console.log('\n✅ Seed completed successfully!')
    console.log(`   - 1 system user`)
    console.log(`   - ${HSK_DECKS.length} HSK decks`)
    console.log(`   - ${TOEIC_DECKS.length} TOEIC decks`)
    console.log(`   - ${GENERAL_DECKS.length} General decks`)
    console.log(`   - Total: ${HSK_DECKS.length + TOEIC_DECKS.length + GENERAL_DECKS.length} decks`)
    
    const totalCards = [...HSK_DECKS, ...TOEIC_DECKS, ...GENERAL_DECKS].reduce((sum, d) => sum + d.cards.length, 0)
    console.log(`   - Total cards: ${totalCards}`)
    
  } catch (error) {
    console.error('❌ Seed failed:', error)
    process.exit(1)
  }
}

main()
